LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

include $(SDK_DIR)/Android.def

LOCAL_PRELINK_MODULE := false

LOCAL_MODULE := libhi_cc
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)

LOCAL_MODULE_TAGS := optional

LOCAL_CFLAGS := $(CFG_HI_CFLAGS)
LOCAL_CFLAGS += -DLOG_TAG=\"$(LOCAL_MODULE)\"

LOCAL_SRC_FILES := $(sort $(call all-c-files-under, ./))
#CURDIR := .
#LOCAL_SRC_FILES := $(CURDIR)/src/hi_unf_cc.c

LOCAL_C_INCLUDES := $(MSP_API_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(MSP_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_UNF_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_DRV_INCLUDE)
LOCAL_C_INCLUDES += $(COMMON_API_INCLUDE)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/arib/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/cc608/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/cc708/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/ccdisp/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/src/common/include

LOCAL_SHARED_LIBRARIES := libcutils libutils libdl libhi_common

include $(BUILD_SHARED_LIBRARY)
