#!/bin/sh

#hme voip test stub
#rmmod hme_drv_stub

#audio adapter
rmmod hi_aud_adp

#voip
rmmod voip_hme

#net adapter
rmmod hi_ndpt

#slic driver
#rmmod wish_slac
#rmmod hi_ssp

#slic driver
#insmod ./hi_ssp.ko
#insmod ./wish_slac.ko

#net adapter
insmod ../../pub/kmod/hi_ndpt.ko

#voip
insmod ../../pub/kmod/voip_hme.ko

#audio adapter
insmod ../../pub/kmod/hi_aud_adp.ko



