#!/bin/sh

#hme voip test stub
#rmmod hme_drv_stub

#audio adapter
rmmod hi_aud_adp

#voip
rmmod voip_hme

#mpi
rmmod hi_svdec
rmmod hifb
rmmod hi_mpi

#net adapter
rmmod hi_ndpt

#slic driver
rmmod wish_slac
rmmod hi_ssp

#slic driver
insmod /kmod/hi_ssp.ko
insmod /kmod/wish_slac.ko

#net adapter
insmod /kmod/hi_ndpt.ko

#mpi
insmod /kmod/hi_mpi.ko
insmod /kmod/hifb.ko
insmod /kmod/hi_svdec.ko

#voip
insmod /kmod/voip_hme.ko

#audio adapter
insmod /kmod/hi_aud_adp.ko



