#!/system/bin/sh

SAVED=`cat /proc/hibernate/saved`

if [ "$SAVED" != "0" ]; then
  exit $SAVED
fi

time busybox killall dhcpcd

#chmod 666 /data/system/wallpaper_info.xml
sync

stop keystore
stop hidns-sd
stop bootanim
/sbin/snapshot -i3$*
start keystore
start hidns-sd
setprop persist.sys.qb.flag true
start bootanim
#rm /tmp_database/sqlite-shm-*

#logcat > /data/log1_back.txt &
setprop sys.insmod.ko 1
setprop sys.qb.reload trigger_load_persist_props
STAT=/proc/hibernate/stat
SAVED=`cat /proc/hibernate/saved`

/system/bin/logwrapper /system/bin/dhcpcd eth0 &

