ifneq ($(CFG_HI_LOADER_APPLOADER),y)
ADEC_DIR := adec
LOCAL_CFLAGS += -DHI_ADEC_MAX_INSTANCE=$(CFG_HI_ADEC_MAX_INSTANCE)
LOCAL_CFLAGS += -DHI_ADEC_OUTPUTBUF_FRAMENUM=$(CFG_HI_ADEC_OUTPUTBUF_FRAMENUM)

ifeq (y,$(CFG_HI_ADEC_AUDSPECTRUM_SUPPORT))
LOCAL_CFLAGS += -DHI_ADEC_AUDSPECTRUM_SUPPORT
LOCAL_SRC_FILES += $(ADEC_DIR)/mpi_adec_waveform.c
endif

LOCAL_SRC_FILES += $(ADEC_DIR)/mpi_adec.c
LOCAL_SRC_FILES += $(ADEC_DIR)/mpi_adec_core.c
LOCAL_C_INCLUDES += $(MSP_DIR)/api/adec
LOCAL_LDFLAGS += $(LOCAL_PATH)/$(ADEC_DIR)/lib/libhi_adec_imple.a
endif
