#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-hisiv200-linux-gcc -DOPENSSL_THREADS  -DB_ENDIAN -fPIC "
  #define PLATFORM "linux"
  #define DATE "Wed Nov 26 19:51:14 HKT 2014"
#endif

