/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2007-2010, 2013, 2015 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */

#ifndef _GLES_INSTRUMENTED_TYPES_H_
#define _GLES_INSTRUMENTED_TYPES_H_

#include "mali_instrumented_counter_types.h"

typedef enum
{
	INST_GL_DRAW_ELEMENTS_CALLS = MALI_GLES_COUNTER_OFFSET,
	INST_GL_DRAW_ELEMENTS_NUM_INDICES,
	INST_GL_DRAW_ELEMENTS_NUM_TRANSFORMED,
	INST_GL_DRAW_ARRAYS_CALLS,
	INST_GL_DRAW_ARRAYS_NUM_TRANSFORMED,
	INST_GL_DRAW_POINTS,
	INST_GL_DRAW_LINES,
	INST_GL_DRAW_LINE_LOOP,
	INST_GL_DRAW_LINE_STRIP,
	INST_GL_DRAW_TRIANGLES,
	INST_GL_DRAW_TRIANGLE_STRIP,
	INST_GL_DRAW_TRIANGLE_FAN,
	INST_GL_NON_VBO_DATA_COPY_TIME,
	INST_GL_UNIFORM_BYTES_COPIED_TO_MALI,
	INST_GL_UPLOAD_TEXTURE_TIME,
	INST_GL_UPLOAD_VBO_TIME,
	INST_GL_NUM_FLUSHES,
	INST_GL_NUM_VSHADERS_GENERATED,
	INST_GL_NUM_FSHADERS_GENERATED,
	INST_GL_VSHADER_GEN_TIME,
	INST_GL_FSHADER_GEN_TIME,
	INST_GL_INPUT_TRIANGLES,
	INST_GL_VXCACHE_HIT,
	INST_GL_VXCACHE_MISS,
	INST_GL_VXCACHE_COLLISION,
	INST_GL_CULLED_TRIANGLES,
	INST_GL_CULLED_LINES,
	INST_GL_BACKFACE_TRIANGLES,
	INST_GL_GBCLIP_TRIANGLES,
	INST_GL_GBCLIP_LINES,
	INST_GL_TRIANGLES_DRAWN,
	INST_GL_DRAWCALL_TIME,
	INST_GL_TRIANGLES_COUNT,
	INST_GL_INDEPENDENT_TRIANGLES_COUNT,
	INST_GL_STRIP_TRIANGLES_COUNT,
	INST_GL_FAN_TRIANGLES_COUNT,
	INST_GL_LINES_COUNT,
	INST_GL_INDEPENDENT_LINES_COUNT,
	INST_GL_STRIP_LINES_COUNT,
	INST_GL_LOOP_LINES_COUNT,
	INST_GL_POINTS_COUNT

} gles_counter;


#endif /* _GLES_INSTRUMENTED_TYPES_H_ */

