/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2007-2011, 2013, 2015 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */

#ifndef _VG_INSTRUMENTED_TYPES_H_
#define _VG_INSTRUMENTED_TYPES_H_

#include "mali_instrumented_counter_types.h"

typedef enum            /* These may be used as CounterIDs */
{
	VG_MASK_COUNTER = MALI_VG_COUNTER_OFFSET,
	VG_CLEAR_COUNTER,
	VG_APPEND_PATH_COUNTER,
	VG_APPEND_PATH_DATA_COUNTER,
	VG_MODIFY_PATH_COORDS_COUNTER,
	VG_TRANSFORM_PATH_COUNTER,
	VG_INTERPOLATE_PATH_COUNTER,
	VG_PATH_LENGTH_COUNTER,
	VG_POINT_ALONG_PATH_COUNTER,
	VG_PATH_BOUNDS_COUNTER,
	VG_PATH_TRANSFORMED_BOUNDS_COUNTER,
	VG_DRAW_PATH_COUNTER,
	VG_CLEAR_IMAGE_COUNTER,
	VG_IMAGE_SUB_DATA_COUNTER,
	VG_GET_IMAGE_SUB_DATA_COUNTER,
	VG_COPY_IMAGE_COUNTER,
	VG_DRAW_IMAGE_COUNTER,
	VG_SET_PIXELS_COUNTER,
	VG_WRITE_PIXELS_COUNTER,
	VG_GET_PIXELS_COUNTER,
	VG_READ_PIXELS_COUNTER,
	VG_COPY_PIXELS_COUNTER,
	VG_COLOR_MATRIX_COUNTER,
	VG_CONVOLVE_COUNTER,
	VG_SEPARABLE_CONVOLVE_COUNTER,
	VG_GAUSSIAN_BLUR_COUNTER,
	VG_LOOKUP_COUNTER,
	VG_LOOKUP_SINGLE_COUNTER,
	VG_CONTEXT_CREATE_COUNTER,
	VG_RENDER_TO_MASK_COUNTER,
	VG_COPY_MASK_COUNTER,
	VG_FILL_MASK_LAYER_COUNTER,

	VG_STROKED_CUBICS_COUNTER,
	VG_STROKED_QUADS_COUNTER,
	VG_STROKED_ARCS_COUNTER,
	VG_STROKED_LINES_COUNTER,
	VG_FILLED_CUBICS_COUNTER,
	VG_FILLED_QUADS_COUNTER,
	VG_FILLED_ARCS_COUNTER,
	VG_FILLED_LINES_COUNTER,

	VG_QUADS_SUBDIV_LIMIT_COUNTER,
	VG_ARCS_SUBDIV_LIMIT_COUNTER,

	VG_QUADS_ONLY_COUNTER,
	VG_ARCS_ONLY_COUNTER,

	VG_DRAW_PATH_CALLS_COUNTER,
	VG_TRIANGLES_COUNTER,
	VG_VERTICES_COUNTER,
	VG_INDICES_COUNTER,
	VG_FILLED_PATHS_COUNTER,
	VG_STROKED_PATHS_COUNTER,

	VG_FILL_EXTRACT_COUNTER,
	VG_DRAW_FILLED_PATH_COUNTER,
	VG_STROKE_EXTRACT_COUNTER,
	VG_DRAW_STROKED_PATH_COUNTER,
	VG_DRAW_PAINT_COUNTER,
	VG_DATA_STRUCTURES_COUNTER,

	VG_MASK_BLIT_COUNTER,
	VG_MASK_PAINT_COUNTER,

	VG_DRAW_GLYPH_COUNTER,
	VG_DRAW_GLYPHS_COUNTER,

	VG_RC_SUBMISSIONS_COUNTER,

	VG_MEM_PATH_COUNTER,
	VG_RSW_COUNTER,
	NUM_VG_COUNTERS
} vg_counter;


#endif /* _VG_INSTRUMENTED_TYPES_H_ */

