/*
 * This confidential and proprietary software may be used only as
 * authorised by a licensing agreement from ARM Limited
 * (C) COPYRIGHT 2008-2010, 2013-2014 ARM Limited
 * ALL RIGHTS RESERVED
 * The entire notice above must be reproduced on all authorised
 * copies and copies may only be made to the extent permitted
 * by a licensing agreement from ARM Limited.
 */

#ifndef _MALIL2_COUNTERS_H_
#define _MALIL2_COUNTERS_H_

#if defined(USING_MALI200)
#error "This functionality is not supported on Mali200"
#endif

#define MALI_L2_GROUP_OFFSET 1000
#define MALI_L2_GP_CORE_OFFSET MALI_L2_GROUP_OFFSET
#define MALI_L2_PP_CORE_OFFSET (MALI_L2_GROUP_OFFSET + MALI_L2_GROUP_OFFSET)
#define MALI_L2_MULTI_CORE_OFFSET MALI_L2_GROUP_OFFSET

#define MALI_L2_NUMBER_OF_HW_COUNTER_REGISTERS 2

enum mali_l2_counter_ids
{
	CID_MALI_L2_TOTAL_CLOCK_CYCLES                     = MALI_L2_COUNTER_OFFSET + 1,
	CID_MALI_L2_ACTIVE_CLOCK_CYCLES                    = MALI_L2_COUNTER_OFFSET + 2,

	CID_MALI_L2_READ_TRANSACTIONS_MASTER               = MALI_L2_COUNTER_OFFSET + 8,
	CID_MALI_L2_WRITE_TRANSACTIONS_MASTER              = MALI_L2_COUNTER_OFFSET + 9,
	CID_MALI_L2_WORDS_READ_MASTER                      = MALI_L2_COUNTER_OFFSET + 10,
	CID_MALI_L2_WORDS_WRITTEN_MASTER                   = MALI_L2_COUNTER_OFFSET + 11,

	CID_MALI_L2_READ_TRANSACTIONS_ALL_SLAVES           = MALI_L2_COUNTER_OFFSET + 16,
	CID_MALI_L2_WRITE_TRANSACTIONS_ALL_SLAVES          = MALI_L2_COUNTER_OFFSET + 17,
	CID_MALI_L2_WORDS_READ_ALL_SLAVES                  = MALI_L2_COUNTER_OFFSET + 18,
	CID_MALI_L2_WORDS_WRITTEN_ALL_SLAVES               = MALI_L2_COUNTER_OFFSET + 19,
	CID_MALI_L2_READ_HITS_ALL_SLAVES                   = MALI_L2_COUNTER_OFFSET + 20,
	CID_MALI_L2_READ_MISSES_ALL_SLAVES                 = MALI_L2_COUNTER_OFFSET + 21,
	CID_MALI_L2_WRITE_INVALIDATES_ALL_SLAVES           = MALI_L2_COUNTER_OFFSET + 22,
	CID_MALI_L2_READ_INVALIDATES_ALL_SLAVES            = MALI_L2_COUNTER_OFFSET + 23,
	CID_MALI_L2_CACHEABLE_READ_TRANSACTIONS_ALL_SLAVES = MALI_L2_COUNTER_OFFSET + 24,

	CID_MALI_L2_READ_TRANSACTIONS_SLAVE_0              = MALI_L2_COUNTER_OFFSET + 32,
	CID_MALI_L2_WRITE_TRANSACTIONS_SLAVE_0             = MALI_L2_COUNTER_OFFSET + 33,
	CID_MALI_L2_WORDS_READ_SLAVE_0                     = MALI_L2_COUNTER_OFFSET + 34,
	CID_MALI_L2_WORDS_WRITTEN_SLAVE_0                  = MALI_L2_COUNTER_OFFSET + 35,
	CID_MALI_L2_READ_HITS_SLAVE_0                      = MALI_L2_COUNTER_OFFSET + 36,
	CID_MALI_L2_READ_MISSES_SLAVE_0                    = MALI_L2_COUNTER_OFFSET + 37,
	CID_MALI_L2_WRITE_INVALIDATES_SLAVE_0              = MALI_L2_COUNTER_OFFSET + 38,
	CID_MALI_L2_READ_INVALIDATES_SLAVE_0               = MALI_L2_COUNTER_OFFSET + 39,
	CID_MALI_L2_CACHEABLE_READ_TRANSACTIONS_SLAVE_0    = MALI_L2_COUNTER_OFFSET + 40,

	CID_MALI_L2_READ_TRANSACTIONS_SLAVE_1              = MALI_L2_COUNTER_OFFSET + 48,
	CID_MALI_L2_WRITE_TRANSACTIONS_SLAVE_1             = MALI_L2_COUNTER_OFFSET + 49,
	CID_MALI_L2_WORDS_READ_SLAVE_1                     = MALI_L2_COUNTER_OFFSET + 50,
	CID_MALI_L2_WORDS_WRITTEN_SLAVE_1                  = MALI_L2_COUNTER_OFFSET + 51,
	CID_MALI_L2_READ_HITS_SLAVE_1                      = MALI_L2_COUNTER_OFFSET + 52,
	CID_MALI_L2_READ_MISSES_SLAVE_1                    = MALI_L2_COUNTER_OFFSET + 53,
	CID_MALI_L2_WRITE_INVALIDATES_SLAVE_1              = MALI_L2_COUNTER_OFFSET + 54,
	CID_MALI_L2_READ_INVALIDATES_SLAVE_1               = MALI_L2_COUNTER_OFFSET + 55,
	CID_MALI_L2_CACHEABLE_READ_TRANSACTIONS_SLAVE_1    = MALI_L2_COUNTER_OFFSET + 56,

	CID_MALI_L2_READ_TRANSACTIONS_SLAVE_2              = MALI_L2_COUNTER_OFFSET + 64,
	CID_MALI_L2_WRITE_TRANSACTIONS_SLAVE_2             = MALI_L2_COUNTER_OFFSET + 65,
	CID_MALI_L2_WORDS_READ_SLAVE_2                     = MALI_L2_COUNTER_OFFSET + 66,
	CID_MALI_L2_WORDS_WRITTEN_SLAVE_2                  = MALI_L2_COUNTER_OFFSET + 67,
	CID_MALI_L2_READ_HITS_SLAVE_2                      = MALI_L2_COUNTER_OFFSET + 68,
	CID_MALI_L2_READ_MISSES_SLAVE_2                    = MALI_L2_COUNTER_OFFSET + 69,
	CID_MALI_L2_WRITE_INVALIDATES_SLAVE_2              = MALI_L2_COUNTER_OFFSET + 70,
	CID_MALI_L2_READ_INVALIDATES_SLAVE_2               = MALI_L2_COUNTER_OFFSET + 71,
	CID_MALI_L2_CACHEABLE_READ_TRANSACTIONS_SLAVE_2    = MALI_L2_COUNTER_OFFSET + 72,

	CID_MALI_L2_READ_TRANSACTIONS_SLAVE_3              = MALI_L2_COUNTER_OFFSET + 80,
	CID_MALI_L2_WRITE_TRANSACTIONS_SLAVE_3             = MALI_L2_COUNTER_OFFSET + 81,
	CID_MALI_L2_WORDS_READ_SLAVE_3                     = MALI_L2_COUNTER_OFFSET + 82,
	CID_MALI_L2_WORDS_WRITTEN_SLAVE_3                  = MALI_L2_COUNTER_OFFSET + 83,
	CID_MALI_L2_READ_HITS_SLAVE_3                      = MALI_L2_COUNTER_OFFSET + 84,
	CID_MALI_L2_READ_MISSES_SLAVE_3                    = MALI_L2_COUNTER_OFFSET + 85,
	CID_MALI_L2_WRITE_INVALIDATES_SLAVE_3              = MALI_L2_COUNTER_OFFSET + 86,
	CID_MALI_L2_READ_INVALIDATES_SLAVE_3               = MALI_L2_COUNTER_OFFSET + 87,
	CID_MALI_L2_CACHEABLE_READ_TRANSACTIONS_SLAVE_3    = MALI_L2_COUNTER_OFFSET + 88,

	CID_MALI_L2_READ_TRANSACTIONS_SLAVE_4              = MALI_L2_COUNTER_OFFSET + 96,
	CID_MALI_L2_WRITE_TRANSACTIONS_SLAVE_4             = MALI_L2_COUNTER_OFFSET + 97,
	CID_MALI_L2_WORDS_READ_SLAVE_4                     = MALI_L2_COUNTER_OFFSET + 98,
	CID_MALI_L2_WORDS_WRITTEN_SLAVE_4                  = MALI_L2_COUNTER_OFFSET + 99,
	CID_MALI_L2_READ_HITS_SLAVE_4                      = MALI_L2_COUNTER_OFFSET + 100,
	CID_MALI_L2_READ_MISSES_SLAVE_4                    = MALI_L2_COUNTER_OFFSET + 101,
	CID_MALI_L2_WRITE_INVALIDATES_SLAVE_4              = MALI_L2_COUNTER_OFFSET + 102,
	CID_MALI_L2_READ_INVALIDATES_SLAVE_4               = MALI_L2_COUNTER_OFFSET + 103,
	CID_MALI_L2_CACHEABLE_READ_TRANSACTIONS_SLAVE_4    = MALI_L2_COUNTER_OFFSET + 104,

	CID_MALI_L2_ENUM_MAX
};

#define MALI_L2_NUMBER_OF_PERFORMANCE_COUNTERS (CID_L2_ENUM_MAX - MALI_L2_COUNTER_OFFSET)
#define MALI_L2_HW_COUNTER_DISABLED 0

#endif /* _MALIL2_COUNTERS_H_ */

