LOCAL_PATH := $(my-dir)

include $(CLEAR_VARS)

# backup default target out
TARGET_OUT_INTERMEDIATES_BAK := $(TARGET_OUT_INTERMEDIATES)
TARGET_OUT_INTERMEDIATE_LIBRARIES_BAK := $(TARGET_OUT_INTERMEDIATE_LIBRARIES)
TARGET_OUT_SHARED_LIBRARIES_BAK := $(TARGET_OUT_SHARED_LIBRARIES)
# change to 32bit target out
ifeq (arm64,$(TARGET_ARCH))
TARGET_OUT_INTERMEDIATES := $(PRODUCT_OUT)/obj_arm
else
TARGET_OUT_INTERMEDIATES := $(PRODUCT_OUT)/obj
endif
TARGET_OUT_INTERMEDIATE_LIBRARIES := $(TARGET_OUT_INTERMEDIATES)/lib
TARGET_OUT_SHARED_LIBRARIES := $(PRODUCT_OUT)/system/lib

LOCAL_MODULES_NAME := libhi_component_common

define addprefixsuffix_so_list
$(addprefix lib/, $(addsuffix .so, $(1)))
endef

LOCAL_PREBUILT_LIBS := $(call addprefixsuffix_so_list,$(LOCAL_MODULES_NAME))

ifeq (5.0,$(findstring 5.0,$(PLATFORM_VERSION)))
    LOCAL_32_BIT_ONLY :=true
else
    ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULES_NAME)
endif

LOCAL_MODULE_TAGS := optional

include $(BUILD_MULTI_PREBUILT)

# resume default target out
include $(CLEAR_VARS)
TARGET_OUT_INTERMEDIATES := $(TARGET_OUT_INTERMEDIATES_BAK)
TARGET_OUT_INTERMEDIATE_LIBRARIES := $(TARGET_OUT_INTERMEDIATE_LIBRARIES_BAK)
TARGET_OUT_SHARED_LIBRARIES := $(TARGET_OUT_SHARED_LIBRARIES_BAK)
include $(BUILD_MULTI_PREBUILT)
