
#by fangjian00208632 2015-03-13

###########################################################
# platform definition
###########################################################
ROOT      =.


##########################################################
# build
##########################################################
.PHONY : all clean
all:
	$(MAKE) -C $(ROOT)/demo_srv/ all
	$(MAKE) -C $(ROOT)/demo_srv1/ all
	$(MAKE) -C $(ROOT)/demo_srv2/ all
	$(MAKE) -C $(ROOT)/demo_srv3/ all
	$(MAKE) -C $(ROOT)/demo_srv4/ all
	$(MAKE) -C $(ROOT)/demo_srv5/ all
	$(MAKE) -C $(ROOT)/demo_srv6/ all
	$(MAKE) -C $(ROOT)/demo_srv7/ all
	$(MAKE) -C $(ROOT)/demo_srv8/ all
	$(MAKE) -C $(ROOT)/demo_srv9/ all
	$(MAKE) -C $(ROOT)/task_QA_TZService/ all
clean:
	$(MAKE) -C $(ROOT)/demo_srv/ clean
	$(MAKE) -C $(ROOT)/demo_srv1/ clean
	$(MAKE) -C $(ROOT)/demo_srv2/ clean
	$(MAKE) -C $(ROOT)/demo_srv3/ clean
	$(MAKE) -C $(ROOT)/demo_srv4/ clean
	$(MAKE) -C $(ROOT)/demo_srv5/ clean
	$(MAKE) -C $(ROOT)/demo_srv6/ clean
	$(MAKE) -C $(ROOT)/demo_srv7/ clean
	$(MAKE) -C $(ROOT)/demo_srv8/ clean
	$(MAKE) -C $(ROOT)/demo_srv9/ clean
	$(MAKE) -C $(ROOT)/task_QA_TZService/ clean
