LOCAL_PATH := $(call my-dir)

include $(SDK_DIR)/Android.def
include $(CLEAR_VARS)

ifeq ($(strip $(CFG_HI_GPU_MALI450_SUPPORT)), y)
GPU_TARGET=mali450
else ifeq ($(strip $(CFG_HI_GPU_MALI400_SUPPORT)), y)
GPU_TARGET=mali400
endif

include $(CLEAR_VARS)
LOCAL_MODULE := libGLES_mali.so
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)
LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
LOCAL_SRC_FILES := $(GPU_TARGET)/libGLES_mali.so
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := egl.cfg
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)
LOCAL_MODULE_TAGS:= optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)/egl
LOCAL_SRC_FILES := $(GPU_TARGET)/egl.cfg
include $(BUILD_PREBUILT)
