ifeq ($(strip $(PRODUCT_TARGET)), demo)
else
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_STATIC_JAVA_LIBRARIES := HiMediaPlayer
LOCAL_STATIC_JAVA_LIBRARIES += FlashInfo
LOCAL_STATIC_JAVA_LIBRARIES += SDKInvoke
LOCAL_STATIC_JAVA_LIBRARIES += DisplaySetting
LOCAL_STATIC_JAVA_LIBRARIES += HiSysManager

LOCAL_SRC_FILES := $(call all-java-files-under, src)
LOCAL_PROGUARD_ENABLED := disabled
LOCAL_PACKAGE_NAME := HiFactoryTest
#ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_PACKAGE_NAME)
LOCAL_CERTIFICATE := platform

#include $(BUILD_PACKAGE)

LOCAL_MODULE_TAGS := optional

include $(CLEAR_VARS)
include $(BUILD_MULTI_PREBUILT)
endif
