/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_com_hisilicon_android_networkupgrade_activity_SDKVersion
#define _Included_com_hisilicon_android_networkupgrade_activity_SDKVersion
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jstring JNICALL Java_com_hisilicon_android_networkupgrade_activity_BuildNumber_GetSDKVersion(JNIEnv *env, jclass clazz);

#ifdef __cplusplus
}
#endif
#endif
