#ifndef _PQ_DEF_H_
#define _PQ_DEF_H_

/* image mode */
typedef enum HI_PQ_IMAGE_MODE
{
     HI_PQ_IMAGE_MODE_STANDARD = 0,
     HI_PQ_IMAGE_MODE_COLORFUL,
     HI_PQ_IMAGE_MODE_THEATER,
     HI_PQ_IMAGE_MODE_SPORT,
     HI_PQ_IMAGE_MODE_CUSTOMIZE,

     HI_PQ_IMAGE_MODE_BUTT
} HI_PQ_IMAGE_MODE_E;

/* color enhance mode */
typedef enum HI_PQ_COLOR_ENHANCE_MODE
{
     HI_PQ_COLOR_ENHANCE_MODE_AUTO = 0,
     HI_PQ_COLOR_ENHANCE_MODE_BLUE,
     HI_PQ_COLOR_ENHANCE_MODE_GREEN,
     HI_PQ_COLOR_ENHANCE_MODE_CYAN,
     HI_PQ_COLOR_ENHANCE_MODE_SKIN,
     HI_PQ_COLOR_ENHANCE_MODE_CUSTOMIZE,

     HI_PQ_COLOR_ENHANCE_MODE_BUTT
} HI_PQ_COLOR_ENHANCE_MODE_E;

/* base color type */
typedef enum HI_PQ_BASE_COLOR_TYPE
{
     HI_PQ_BASE_COLOR_TYPE_RED = 0,
     HI_PQ_BASE_COLOR_TYPE_BLUE,
     HI_PQ_BASE_COLOR_TYPE_GREEN,
     HI_PQ_BASE_COLOR_TYPE_CYAN,
     HI_PQ_BASE_COLOR_TYPE_MAGENTA,
     HI_PQ_BASE_COLOR_TYPE_YELLOW,

     HI_PQ_BASE_COLOR_TYPE_BUTT
} HI_PQ_BASE_COLOR_TYPE_E;

/* dynamic contrast mode */
typedef enum HI_PQ_DYNAMIC_CONTRAST_MODE
{
     HI_PQ_DYNAMIC_CONTRAST_MODE_OFF = 0,
     HI_PQ_DYNAMIC_CONTRAST_MODE_LOW,
     HI_PQ_DYNAMIC_CONTRAST_MODE_MIDDLE,
     HI_PQ_DYNAMIC_CONTRAST_MODE_HIGH,

     HI_PQ_DYNAMIC_CONTRAST_MODE_BUTT
} HI_PQ_DYNAMIC_CONTRAST_MODE_E;

/* save type */
typedef enum HI_PQ_SAVE_TYPE
{
    HI_PQ_SAVE_TYPE_IMAGE = 0,
    HI_PQ_SAVE_TYPE_COLOR,
    HI_PQ_SAVE_TYPE_SHARPNESS,
    HI_PQ_SAVE_TYPE_DYNCCONTRAST,
    HI_PQ_SAVE_TYPE_SHOPMODE,
    HI_PQ_SAVE_TYPE_SUPERRESOLUTION
} HI_PQ_SAVE_TYPE_E;

#endif
