	.arch armv7-a
	.fpu softvfp
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 2
	.eabi_attribute 18, 4
	.file	"sw_main.c"
@ GNU C (Hisilicon_v200(gcc4.4-290+glibc-2.11+eabi+nptl)) version 4.4.1 (arm-hisiv200-linux-gnueabi)
@	compiled by GNU C version 4.1.1 20061011 (Red Hat 4.1.1-30), GMP version 4.3.1, MPFR version 2.4.2.
@ GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
@ options passed:  -nostdinc
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/include
@ -Iarch/arm/include/generated
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include
@ -Iinclude
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/include/uapi
@ -Iarch/arm/include/generated/uapi
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/uapi
@ -Iinclude/generated/uapi
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1
@ -Idrivers/msp/adsp/adsp_v1_1
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/mach-hi3798mx/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/api/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/drv/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/api/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/component/ha_codec/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/component/ha_effect/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/include/comp
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/common/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/aoe/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/aflt/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/aoe/src/include
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/component/codec/iapcm_dec
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/component/codec/iamp3_dec
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/component/effect/base_effect
@ -I/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1
@ -imultilib armv7a_soft -iprefix
@ /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../lib/gcc/arm-hisiv200-linux-gnueabi/4.4.1/
@ -isysroot /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../target
@ -D__KERNEL__ -D__LINUX_ARM_ARCH__=7 -Uarm -DCHIP_TYPE_hi3796mv100
@ -DSDK_VERSION=HiSTBAndroidV600R001C00SPC060_v2015040918 -DHI_MCE_SUPPORT
@ -DHI_GPIOI2C_SUPPORT -DHI_LOG_SUPPORT=1 -DHI_LOG_LEVEL=4
@ -DHI_PROC_SUPPORT=1 -DHI_HDMI_SUPPORT_1_4 -DHI_KEYLED_SUPPORT
@ -DHI_HDCP_SUPPORT -DHI_SCI_SUPPORT -DHI_PVR_SUPPORT -DHI_VI_SUPPORT
@ -DHI_VENC_SUPPORT -DHI_AENC_SUPPORT -DHI_PQ_V3_0
@ -DHI_SND_AOE_SWSIMULATE_SUPPORT -DHI_SND_AFLT_SWSIMULATE_SUPPORT
@ -DINTERLEAVED_OUTPUT -DPCM_DECODER_SUPPORT -DBASE_EFFECT_SUPPORT
@ -DHI_SND_TIMER_CAST -DKBUILD_STR(s)=#s
@ -DKBUILD_BASENAME=KBUILD_STR(sw_main)
@ -DKBUILD_MODNAME=KBUILD_STR(hi_adsp) -isystem
@ /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../lib/gcc/arm-hisiv200-linux-gnueabi/4.4.1/include
@ -include
@ /hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/linux/kconfig.h
@ -MD drivers/msp/adsp/adsp_v1_1/./hifi/.sw_main.o.d
@ /hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c
@ -mlittle-endian -mapcs -mno-sched-prolog -mabi=aapcs-linux
@ -mno-thumb-interwork -marm -march=armv7-a -msoft-float -auxbase-strip
@ drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.o -O2 -Wall -Wundef
@ -Wstrict-prototypes -Wno-trigraphs -Werror-implicit-function-declaration
@ -Wno-format-security -Wframe-larger-than=1024
@ -Wdeclaration-after-statement -Wno-pointer-sign -p -fno-strict-aliasing
@ -fno-common -fno-delete-null-pointer-checks -fno-dwarf2-cfi-asm
@ -funwind-tables -fno-stack-protector -fno-omit-frame-pointer
@ -fno-optimize-sibling-calls -fno-strict-overflow -fconserve-stack
@ -fverbose-asm
@ options enabled:  -falign-loops -fargument-alias -fauto-inc-dec
@ -fbranch-count-reg -fcaller-saves -fcprop-registers -fcrossjumping
@ -fcse-follow-jumps -fdefer-pop -fearly-inlining
@ -feliminate-unused-debug-types -fexpensive-optimizations
@ -fforward-propagate -ffunction-cse -fgcse -fgcse-lm
@ -fguess-branch-probability -fident -fif-conversion -fif-conversion2
@ -findirect-inlining -finline -finline-functions-called-once
@ -finline-small-functions -fipa-cp -fipa-pure-const -fipa-reference
@ -fira-share-save-slots -fira-share-spill-slots -fivopts
@ -fkeep-static-consts -fleading-underscore -fmath-errno -fmerge-constants
@ -fmerge-debug-strings -fmove-loop-invariants -foptimize-register-move
@ -fpeephole -fpeephole2 -fprofile -fpromote-loop-indices
@ -freg-struct-return -fregmove -frename-registers -freorder-blocks
@ -freorder-functions -frerun-cse-after-loop -fsched-interblock
@ -fsched-spec -fsched-stalled-insns-dep -fschedule-insns -fschedule-insns2
@ -fsection-anchors -fsigned-zeros -fsplit-ivs-in-unroller
@ -fsplit-wide-types -fthread-jumps -ftoplevel-reorder -ftrapping-math
@ -ftree-builtin-call-dce -ftree-ccp -ftree-ch -ftree-copy-prop
@ -ftree-copyrename -ftree-cselim -ftree-dce -ftree-dominator-opts
@ -ftree-dse -ftree-fre -ftree-loop-im -ftree-loop-ivcanon
@ -ftree-loop-optimize -ftree-parallelize-loops= -ftree-pre -ftree-reassoc
@ -ftree-scev-cprop -ftree-sink -ftree-sra -ftree-switch-conversion
@ -ftree-ter -ftree-vect-loop-version -ftree-vrp -funit-at-a-time
@ -funroll-loops -funwind-tables -fverbose-asm -fweb
@ -fzero-initialized-in-bss -mapcs-frame -mglibc -mlittle-endian

@ Compiler executable checksum: fa59e0bd179ef45b3a3c3e6f3383fdac

	.text
	.align	2
	.global	AFLT_SwEngineDestory
	.type	AFLT_SwEngineDestory, %function
AFLT_SwEngineDestory:
	.fnstart
.LFB1428:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp134,
	movt	r3, #:upper16:.LANCHOR0	@ tmp134,
	mov	r4, #0	@ tmp135,
	mov	r0, #10	@,
	str	r4, [r3, #0]	@ tmp135, g_AfltTaskstate
	bl	msleep	@
	mov	r0, r4	@, tmp135
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AFLT_SwEngineDestory, .-AFLT_SwEngineDestory
	.align	2
	.global	AFLT_SwEngineCreate
	.type	AFLT_SwEngineCreate, %function
AFLT_SwEngineCreate:
	.fnstart
.LFB1427:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, r5, r6, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, r5, r6, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r5, #0	@ tmp140,
	movw	r4, #:lower16:.LANCHOR0	@ tmp148,
	movt	r4, #:upper16:.LANCHOR0	@ tmp148,
	mov	r1, r5	@, tmp140
	mvn	r2, #0	@,
	movw	r0, #:lower16:AfltEngineTask	@,
	movw	r3, #:lower16:.LC0	@,
	movt	r0, #:upper16:AfltEngineTask	@,
	movt	r3, #:upper16:.LC0	@,
	mov	ip, #1	@ tmp138,
	str	r5, [r4, #4]	@ tmp140, g_AfltRunningFlag
	str	ip, [r4, #0]	@ tmp138, g_AfltTaskstate
	bl	kthread_create_on_node	@
	movw	r6, #:lower16:-1515870811	@ tmp150,
	movt	r6, #:upper16:-1515870811	@ tmp150,
	str	r0, [r4, #8]	@, g_pstAFLTEThread
	bl	wake_up_process	@
	b	.L5	@
.L11:
	bl	msleep	@
	ldr	r1, [r4, #4]	@ g_AfltRunningFlag, g_AfltRunningFlag
	mov	r0, #1	@,
	cmp	r1, r6	@ g_AfltRunningFlag, tmp150
	beq	.L4	@,
	bl	msleep	@
	cmp	r5, #512	@ cnt,
	beq	.L4	@,
.L5:
	ldr	r3, [r4, #4]	@ g_AfltRunningFlag, g_AfltRunningFlag
	mov	r0, #1	@,
	add	r5, r5, r0	@ tmp152, cnt,
	cmp	r3, r6	@ g_AfltRunningFlag, tmp150
	add	r5, r5, r0	@ cnt, tmp152,
	bne	.L11	@,
.L4:
	mov	r0, #0	@,
	ldmfd	sp, {r3, r4, r5, r6, fp, sp, pc}	@
	.fnend
	.size	AFLT_SwEngineCreate, .-AFLT_SwEngineCreate
	.align	2
	.type	AfltEngineTask, %function
AfltEngineTask:
	.fnstart
.LFB1426:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #12
	sub	sp, sp, #12	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	ip, sp	@,
	bic	r0, ip, #8128	@ tmp144,,
	sub	r2, fp, #20	@ tmp147,,
	bic	r4, r0, #63	@ tmp144, tmp144,
	mov	lr, #99	@ tmp143,
	mov	r1, #1	@,
	str	lr, [r2, #-4]!	@ tmp143, param.sched_priority
	ldr	r0, [r4, #12]	@, <variable>.task
	bl	sched_setscheduler	@
	ldr	r3, [r4, #12]	@ temp.524, <variable>.task
	mov	r0, #1	@ tmp154,
	ldr	r1, [r3, #12]	@ <variable>.flags, <variable>.flags
	orr	r2, r1, #32768	@ tmp151, <variable>.flags,
	str	r2, [r3, #12]	@ tmp151, <variable>.flags
	ldr	ip, [r4, #12]	@ temp.525, <variable>.task
	str	r0, [ip, #0]	@ tmp154, <variable>.state
#APP
@ 308 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	dmb
@ 0 "" 2
	movw	r4, #:lower16:.LANCHOR0	@ tmp168,
	movt	r4, #:upper16:.LANCHOR0	@ tmp168,
	bl	AFLT_Init	@
	movw	r3, #:lower16:-1515870811	@ tmp158,
	ldr	r2, [r4, #0]	@ g_AfltTaskstate, g_AfltTaskstate
	mov	r1, #0	@ tmp156,
	movt	r3, #:upper16:-1515870811	@ tmp158,
	str	r1, [r4, #12]	@ tmp156, task_bug
	cmp	r2, #1	@ g_AfltTaskstate,
	str	r3, [r4, #4]	@ tmp158, g_AfltRunningFlag
	bne	.L13	@,
.L16:
	bl	AFLT_ProcThread_Sw	@
	mov	r0, #5	@,
	bl	msecs_to_jiffies	@
	bl	schedule_timeout_interruptible	@
	ldr	r2, [r4, #0]	@ g_AfltTaskstate, g_AfltTaskstate
	cmp	r2, #1	@ g_AfltTaskstate,
	beq	.L16	@,
.L13:
	mov	r4, sp	@,
	bic	lr, r4, #8128	@ tmp163,,
	bic	r1, lr, #63	@ tmp163, tmp163,
	mov	r4, #0	@ tmp165,
	ldr	r3, [r1, #12]	@ temp.526, <variable>.task
	str	r4, [r3, #0]	@ tmp165, <variable>.state
#APP
@ 320 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	dmb
@ 0 "" 2
	bl	AFLT_DeInit	@
	mov	r0, r4	@, tmp165
	sub	sp, fp, #16
	ldmfd	sp, {r4, fp, sp, pc}
	.fnend
	.size	AfltEngineTask, .-AfltEngineTask
	.align	2
	.global	AOE_SwEngineDestory
	.type	AOE_SwEngineDestory, %function
AOE_SwEngineDestory:
	.fnstart
.LFB1425:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp134,
	movt	r3, #:upper16:.LANCHOR0	@ tmp134,
	mov	r4, #0	@ tmp135,
	str	r4, [r3, #16]	@ tmp135, g_AoeTaskstate
	bl	TIMER_SetDisable	@
	bl	TIMER_DeInit	@
	mov	r0, #10	@,
	bl	msleep	@
	mov	r0, r4	@, tmp135
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_SwEngineDestory, .-AOE_SwEngineDestory
	.align	2
	.global	AOE_SwEngineCreate
	.type	AOE_SwEngineCreate, %function
AOE_SwEngineCreate:
	.fnstart
.LFB1424:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, r5, r6, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, r5, r6, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r5, #0	@ tmp139,
	movw	r4, #:lower16:.LANCHOR0	@ tmp147,
	movt	r4, #:upper16:.LANCHOR0	@ tmp147,
	mov	r1, r5	@, tmp139
	mvn	r2, #0	@,
	movw	r0, #:lower16:AoEngineTask	@,
	movw	r3, #:lower16:.LC1	@,
	movt	r0, #:upper16:AoEngineTask	@,
	movt	r3, #:upper16:.LC1	@,
	mov	ip, #1	@ tmp137,
	str	r5, [r4, #20]	@ tmp139, g_AoeRunningFlag
	str	ip, [r4, #16]	@ tmp137, g_AoeTaskstate
	bl	kthread_create_on_node	@
	movw	r6, #:lower16:-1515870811	@ tmp149,
	movt	r6, #:upper16:-1515870811	@ tmp149,
	str	r0, [r4, #24]	@, g_pstAOEThread
	bl	wake_up_process	@
	bl	TIMER_Init	@
	bl	TIMER_SetEnable	@
	b	.L22	@
.L27:
	bl	msleep	@
	ldr	r1, [r4, #20]	@ g_AoeRunningFlag, g_AoeRunningFlag
	mov	r0, #1	@,
	cmp	r1, r6	@ g_AoeRunningFlag, tmp149
	beq	.L21	@,
	bl	msleep	@
	cmp	r5, #512	@ cnt,
	beq	.L21	@,
.L22:
	ldr	r3, [r4, #20]	@ g_AoeRunningFlag, g_AoeRunningFlag
	mov	r0, #1	@,
	add	r5, r5, r0	@ tmp151, cnt,
	cmp	r3, r6	@ g_AoeRunningFlag, tmp149
	add	r5, r5, r0	@ cnt, tmp151,
	bne	.L27	@,
.L21:
	mov	r0, #0	@,
	ldmfd	sp, {r3, r4, r5, r6, fp, sp, pc}	@
	.fnend
	.size	AOE_SwEngineCreate, .-AOE_SwEngineCreate
	.align	2
	.global	SchedStatisticsInit
	.type	SchedStatisticsInit, %function
SchedStatisticsInit:
	.fnstart
.LFB1420:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp133,
	movt	r3, #:upper16:.LANCHOR0	@ tmp133,
	mov	r2, #0	@ tmp139,
	mov	r0, #0	@ tmp134,
	mov	r1, #0	@,
	str	r2, [r3, #52]	@ tmp139, g_u32cnt
	strd	r0, [r3, #40]	@ tmp134, tmp133,
	strd	r0, [r3, #32]	@ tmp134, tmp133,
	strh	r2, [r3, #48]	@ movhi	@ tmp139, g_u16SchTimeoutCnt
	strh	r2, [r3, #50]	@ movhi	@ tmp139, g_u16ExcuteTimeoutCnt
	bl	AOE_SchedStatisticsInit	@
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	SchedStatisticsInit, .-SchedStatisticsInit
	.align	2
	.global	SYS_GetLocalCurPts
	.type	SYS_GetLocalCurPts, %function
SYS_GetLocalCurPts:
	.fnstart
.LFB1418:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #8
	sub	sp, sp, #8	@,,
	bl	sched_clock	@
	mov	r7, r1	@ u64TimeNow,
	movw	r1, #:lower16:.LANCHOR0	@ tmp157,
	movt	r1, #:upper16:.LANCHOR0	@ tmp157,
	mov	r6, r0	@ u64TimeNow,
	ldrd	r2, [r1, #56]	@ u64TimeLast, tmp157,
	cmp	r7, r3	@ u64TimeNow, u64TimeLast
	cmpeq	r6, r2	@ u64TimeNow, u64TimeLast
	bcs	.L34	@,
	ldrd	r2, [r1, #64]	@ u64TimeBase, tmp157,
	mvn	r4, #0	@,
	movw	r5, #:lower16:4194303	@,
	movt	r5, #:upper16:4194303	@,
	adds	r4, r4, r2	@,, u64TimeBase
	adc	r5, r5, r3	@,, u64TimeBase
	strd	r4, [fp, #-44]	@,,
	strd	r4, [r1, #64]	@, tmp157,
.L32:
	mov	r2, #0	@ tmp147,
	movw	r4, #:lower16:-1924145349	@,
	mov	ip, r2	@ __z, tmp147
	movt	r4, #:upper16:-1924145349	@,
	movw	r5, #:lower16:-2095944041	@,
	movt	r5, #:upper16:-2095944041	@,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umull	r8, r9, r4, r6	@,, u64TimeNow
	cmn	r8, r4	@,
	adcs	r9, r9, r5	@,
	adc	r8, r2, #0	@, tmp147
@ 0 "" 2
	mov	r2, r8	@ __res,
	mov	r3, r9	@ __res,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umlal	r3, r2, r5, r6	@ __res,, u64TimeNow
	umlal	r3, ip, r4, r7	@ __res, __z,, u64TimeNow
	mov	r3, #0	@ __res
	adds	r2, ip, r2	@ __res, __z
	adc	r3, r3, #0	@ __res
	umlal	r2, r3, r5, r7	@ __res,, u64TimeNow
@ 0 "" 2
	mov	r8, r2, lsr #9	@ tmp152, __res,
	strd	r6, [r1, #56]	@ u64TimeNow, tmp157,
	orr	r1, r8, r3, asl #23	@, tmp152, tmp152, __res,
	ldrd	r8, [fp, #-44]	@,,
	mov	r0, r3, lsr #9	@, __res,
	adds	r4, r1, r8	@ tmp150, tmp152,
	adc	r5, r0, r9	@,,
	mov	r0, r4	@, tmp150
	mov	r1, r5	@,
	sub	sp, fp, #36
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, fp, sp, pc}
.L34:
	ldrd	r2, [r1, #64]	@, tmp157,
	strd	r2, [fp, #-44]	@,,
	b	.L32	@
	.fnend
	.size	SYS_GetLocalCurPts, .-SYS_GetLocalCurPts
	.align	2
	.global	SYS_GetTimeStampUs
	.type	SYS_GetTimeStampUs, %function
SYS_GetTimeStampUs:
	.fnstart
.LFB1419:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #8
	sub	sp, sp, #8	@,,
	bl	sched_clock	@
	mov	r7, r1	@ u64TimeNow,
	movw	r1, #:lower16:.LANCHOR0	@ tmp157,
	movt	r1, #:upper16:.LANCHOR0	@ tmp157,
	mov	r6, r0	@ u64TimeNow,
	ldrd	r2, [r1, #56]	@ u64TimeLast, tmp157,
	cmp	r7, r3	@ u64TimeNow, u64TimeLast
	cmpeq	r6, r2	@ u64TimeNow, u64TimeLast
	bcs	.L39	@,
	ldrd	r2, [r1, #64]	@ u64TimeBase, tmp157,
	mvn	r4, #0	@,
	movw	r5, #:lower16:4194303	@,
	movt	r5, #:upper16:4194303	@,
	adds	r4, r4, r2	@,, u64TimeBase
	adc	r5, r5, r3	@,, u64TimeBase
	strd	r4, [fp, #-44]	@,,
	strd	r4, [r1, #64]	@, tmp157,
.L37:
	mov	r2, #0	@ tmp147,
	movw	r4, #:lower16:-1924145349	@,
	mov	ip, r2	@ __z, tmp147
	movt	r4, #:upper16:-1924145349	@,
	movw	r5, #:lower16:-2095944041	@,
	movt	r5, #:upper16:-2095944041	@,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umull	r8, r9, r4, r6	@,, u64TimeNow
	cmn	r8, r4	@,
	adcs	r9, r9, r5	@,
	adc	r8, r2, #0	@, tmp147
@ 0 "" 2
	mov	r2, r8	@ __res,
	mov	r3, r9	@ __res,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umlal	r3, r2, r5, r6	@ __res,, u64TimeNow
	umlal	r3, ip, r4, r7	@ __res, __z,, u64TimeNow
	mov	r3, #0	@ __res
	adds	r2, ip, r2	@ __res, __z
	adc	r3, r3, #0	@ __res
	umlal	r2, r3, r5, r7	@ __res,, u64TimeNow
@ 0 "" 2
	mov	r8, r2, lsr #9	@ tmp152, __res,
	strd	r6, [r1, #56]	@ u64TimeNow, tmp157,
	orr	r1, r8, r3, asl #23	@, tmp152, tmp152, __res,
	ldrd	r8, [fp, #-44]	@,,
	mov	r0, r3, lsr #9	@, __res,
	adds	r4, r1, r8	@ tmp150, tmp152,
	adc	r5, r0, r9	@,,
	mov	r0, r4	@, tmp150
	mov	r1, r5	@,
	sub	sp, fp, #36
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, fp, sp, pc}
.L39:
	ldrd	r2, [r1, #64]	@, tmp157,
	strd	r2, [fp, #-44]	@,,
	b	.L37	@
	.fnend
	.size	SYS_GetTimeStampUs, .-SYS_GetTimeStampUs
	.align	2
	.global	SchedStatisticsStop
	.type	SchedStatisticsStop, %function
SchedStatisticsStop:
	.fnstart
.LFB1422:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #20
	sub	sp, sp, #20	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	sl, r0	@ enStatistics, enStatistics
	bl	sched_clock	@
	movw	r3, #:lower16:.LANCHOR0	@ tmp175,
	movt	r3, #:upper16:.LANCHOR0	@ tmp175,
	ldrd	r6, [r3, #56]	@ u64TimeLast, tmp175,
	cmp	r1, r7	@ u64TimeNow, u64TimeLast
	cmpeq	r0, r6	@ u64TimeNow, u64TimeLast
	bcc	.L41	@,
	ldrd	r4, [r3, #64]	@, tmp175,
	strd	r4, [fp, #-52]	@,,
.L42:
	mov	r7, #0	@ tmp151,
	strd	r0, [r3, #56]	@ u64TimeNow, tmp175,
	mov	ip, r7	@ __z, tmp151
	movw	r8, #:lower16:-1924145349	@,
	movw	r9, #:lower16:-2095944041	@,
	movt	r8, #:upper16:-1924145349	@,
	movt	r9, #:upper16:-2095944041	@,
	ldr	lr, [r3, #32]	@ g_u64BeginPts, g_u64BeginPts
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umull	r4, r5, r8, r0	@,, u64TimeNow
	cmn	r4, r8	@,
	adcs	r5, r5, r9	@,
	adc	r4, r7, #0	@, tmp151
@ 0 "" 2
	mov	r6, r4	@ __res,
	mov	r7, r5	@ __res,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umlal	r7, r6, r9, r0	@ __res,, u64TimeNow
	umlal	r7, ip, r8, r1	@ __res, __z,, u64TimeNow
	mov	r7, #0	@ __res
	adds	r6, ip, r6	@ __res, __z
	adc	r7, r7, #0	@ __res
	umlal	r6, r7, r9, r1	@ __res,, u64TimeNow
@ 0 "" 2
	ldrd	r0, [fp, #-52]	@,,
	mov	r2, r6, lsr #9	@ tmp155, __res,
	orr	r8, r2, r7, asl #23	@, tmp155, tmp155, __res,
	movw	r6, #:lower16:274877907	@ tmp162,
	adds	r8, r8, r0	@ u64PtsCur, tmp155,
	movt	r6, #:upper16:274877907	@ tmp162,
	rsb	ip, lr, r8	@ tmp159, g_u64BeginPts, u64PtsCur
	mov	r9, r7, lsr #9	@, __res,
	adc	r9, r9, r1	@ u64PtsCur,,
	cmp	sl, #0	@ enStatistics,
	umull	r1, r2, r6, ip	@, tmp161, tmp162, tmp159
	strd	r8, [r3, #40]	@ u64PtsCur, tmp175,
	movw	r3, #:lower16:.LANCHOR0	@ tmp149,
	movt	r3, #:upper16:.LANCHOR0	@ tmp149,
	mov	r6, r2, lsr #6	@ u32Time, tmp161,
	bne	.L43	@,
	cmp	r6, #4	@ u32Time,
	bhi	.L46	@,
.L45:
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L43:
	cmp	sl, #1	@ enStatistics,
	bne	.L45	@,
	cmp	r6, #41	@ u32Time,
	bls	.L45	@,
	ldrh	ip, [r3, #48]	@ g_u16SchTimeoutCnt, g_u16SchTimeoutCnt
	mov	r0, sl	@, enStatistics
	add	r2, ip, #1	@ tmp171, g_u16SchTimeoutCnt,
	uxth	r1, r2	@ g_u16SchTimeoutCnt.439, tmp171
	strh	r1, [r3, #48]	@ movhi	@ g_u16SchTimeoutCnt.439, g_u16SchTimeoutCnt
	bl	AOE_SchedStatisticsShow	@
	cmp	r6, #100	@ u32Time,
	bls	.L45	@,
	movw	r2, #:lower16:.LANCHOR1	@,
	mov	r0, #2	@,
	movt	r2, #:upper16:.LANCHOR1	@,
	mov	r1, #26	@,
	mov	r3, #171	@,
	str	r6, [sp, #4]	@ u32Time,
	movw	lr, #:lower16:.LC2	@ tmp174,
	movt	lr, #:upper16:.LC2	@ tmp174,
	str	lr, [sp, #0]	@ tmp174,
	bl	HI_LogOut	@
	b	.L45	@
.L41:
	ldrd	r6, [r3, #64]	@ u64TimeBase, tmp175,
	mvn	r8, #0	@,
	movw	r9, #:lower16:4194303	@,
	movt	r9, #:upper16:4194303	@,
	adds	r8, r8, r6	@,, u64TimeBase
	adc	r9, r9, r7	@,, u64TimeBase
	strd	r8, [fp, #-52]	@,,
	strd	r8, [r3, #64]	@, tmp175,
	b	.L42	@
.L46:
	ldrh	lr, [r3, #50]	@ g_u16ExcuteTimeoutCnt, g_u16ExcuteTimeoutCnt
	mov	r0, sl	@, enStatistics
	add	r1, lr, #1	@ tmp166, g_u16ExcuteTimeoutCnt,
	uxth	r1, r1	@ g_u16ExcuteTimeoutCnt.437, tmp166
	strh	r1, [r3, #50]	@ movhi	@ g_u16ExcuteTimeoutCnt.437, g_u16ExcuteTimeoutCnt
	bl	AOE_SchedStatisticsShow	@
	b	.L45	@
	.fnend
	.size	SchedStatisticsStop, .-SchedStatisticsStop
	.align	2
	.global	SchedStatisticsStart
	.type	SchedStatisticsStart, %function
SchedStatisticsStart:
	.fnstart
.LFB1421:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #8
	sub	sp, sp, #8	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	bl	sched_clock	@
	movw	r3, #:lower16:.LANCHOR0	@ tmp155,
	movt	r3, #:upper16:.LANCHOR0	@ tmp155,
	ldrd	r4, [r3, #56]	@ u64TimeLast, tmp155,
	cmp	r1, r5	@ u64TimeNow, u64TimeLast
	cmpeq	r0, r4	@ u64TimeNow, u64TimeLast
	bcs	.L51	@,
	ldrd	r4, [r3, #64]	@ u64TimeBase, tmp155,
	mvn	r6, #0	@,
	movw	r7, #:lower16:4194303	@,
	movt	r7, #:upper16:4194303	@,
	adds	r6, r6, r4	@,, u64TimeBase
	adc	r7, r7, r5	@,, u64TimeBase
	strd	r6, [fp, #-44]	@,,
	strd	r6, [r3, #64]	@, tmp155,
.L49:
	mov	r4, #0	@ tmp147,
	movw	r6, #:lower16:-1924145349	@,
	mov	lr, r4	@ __z, tmp147
	movt	r6, #:upper16:-1924145349	@,
	movw	r7, #:lower16:-2095944041	@,
	movt	r7, #:upper16:-2095944041	@,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umull	r8, r9, r6, r0	@,, u64TimeNow
	cmn	r8, r6	@,
	adcs	r9, r9, r7	@,
	adc	r8, r4, #0	@, tmp147
@ 0 "" 2
	mov	r4, r8	@ __res,
	mov	r5, r9	@ __res,
#APP
@ 105 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	umlal	r5, r4, r7, r0	@ __res,, u64TimeNow
	umlal	r5, lr, r6, r1	@ __res, __z,, u64TimeNow
	mov	r5, #0	@ __res
	adds	r4, lr, r4	@ __res, __z
	adc	r5, r5, #0	@ __res
	umlal	r4, r5, r7, r1	@ __res,, u64TimeNow
@ 0 "" 2
	mov	r8, r4, lsr #9	@ tmp152, __res,
	mov	r2, r5, lsr #9	@, __res,
	orr	ip, r8, r5, asl #23	@, tmp152, tmp152, __res,
	ldrd	r8, [fp, #-44]	@,,
	strd	r0, [r3, #56]	@ u64TimeNow, tmp155,
	adds	r6, ip, r8	@ tmp154, tmp152,
	adc	r7, r2, r9	@,,
	strd	r6, [r3, #32]	@ tmp154, tmp155,
	sub	sp, fp, #36
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, fp, sp, pc}
.L51:
	ldrd	r4, [r3, #64]	@, tmp155,
	strd	r4, [fp, #-44]	@,,
	b	.L49	@
	.fnend
	.size	SchedStatisticsStart, .-SchedStatisticsStart
	.align	2
	.type	AoEngineTask, %function
AoEngineTask:
	.fnstart
.LFB1423:
	@ args = 0, pretend = 0, frame = 16
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #20
	sub	sp, sp, #20	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	ip, sp	@,
	bic	r4, ip, #8128	@ tmp149,,
	sub	r2, fp, #44	@ tmp152,,
	bic	r4, r4, #63	@ tmp149, tmp149,
	mov	sl, #99	@ tmp148,
	mov	r1, #1	@,
	str	sl, [r2, #-4]!	@ tmp148, param.sched_priority
	ldr	r0, [r4, #12]	@, <variable>.task
	mov	sl, #2	@ tmp159,
	bl	sched_setscheduler	@
	ldr	r6, [r4, #12]	@ temp.724, <variable>.task
	ldr	r7, [r6, #12]	@ <variable>.flags, <variable>.flags
	orr	r1, r7, #32768	@ tmp156, <variable>.flags,
	str	r1, [r6, #12]	@ tmp156, <variable>.flags
	ldr	r0, [r4, #12]	@ temp.725, <variable>.task
	str	sl, [r0, #0]	@ tmp159, <variable>.state
#APP
@ 189 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	dmb
@ 0 "" 2
	movw	r5, #:lower16:.LANCHOR1	@ tmp164,
	movt	r5, #:upper16:.LANCHOR1	@ tmp164,
	bl	AOE_Init	@
	movw	r8, #:lower16:5000000	@ D.26628,
	bl	SchedStatisticsInit	@
	ldrd	r0, [r5, #24]	@ ktime_zero.tv64, tmp164,
	movt	r8, #:upper16:5000000	@ D.26628,
	movw	r6, #:lower16:.LANCHOR0	@ tmp176,
	adds	r8, r8, r0	@ D.26628, D.26628, ktime_zero.tv64
	movt	r6, #:upper16:.LANCHOR0	@ tmp176,
	mov	r9, #0	@ D.26628,
	sub	r7, fp, #60	@ tmp181,,
	adc	r9, r9, r1	@ D.26628, D.26628, ktime_zero.tv64
	mov	r2, #0	@ tmp161,
	movw	r3, #:lower16:-1515870811	@ tmp163,
	str	r2, [r6, #72]	@ tmp161, task_bug
	movt	r3, #:upper16:-1515870811	@ tmp163,
	str	r3, [r6, #20]	@ tmp163, g_AoeRunningFlag
.L58:
	ldr	r5, [r6, #16]	@ g_AoeTaskstate, g_AoeTaskstate
	mov	r0, #0	@,
	cmp	r5, #1	@ g_AoeTaskstate,
	bne	.L59	@,
.L54:
	bl	SchedStatisticsStart	@
	bl	AOE_ProcThread_Sw	@
	mov	r0, #0	@,
	bl	SchedStatisticsStop	@
	bl	AOE_GetThreadStatus	@
	cmp	r0, #1	@,
	mov	r0, r5	@, g_AoeTaskstate
	beq	.L58	@,
	bl	SchedStatisticsStart	@
	ldr	r3, [r4, #12]	@ temp.726, <variable>.task
	strd	r8, [fp, #-60]	@ D.26628,,
	str	sl, [r3, #0]	@ tmp180, <variable>.state
#APP
@ 232 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	dmb
@ 0 "" 2
	mov	r1, r5	@, g_AoeTaskstate
	mov	r0, r7	@, tmp181
	bl	schedule_hrtimeout	@
	mov	r0, r5	@, g_AoeTaskstate
	bl	SchedStatisticsStop	@
	ldr	r5, [r6, #16]	@ g_AoeTaskstate, g_AoeTaskstate
	mov	r0, #0	@,
	cmp	r5, #1	@ g_AoeTaskstate,
	beq	.L54	@,
.L59:
	mov	r4, sp	@,
	bic	r1, r4, #8128	@ tmp172,,
	bic	r2, r1, #63	@ tmp172, tmp172,
	mov	r4, r0	@ tmp174,
	ldr	lr, [r2, #12]	@ temp.727, <variable>.task
	str	r0, [lr, #0]	@ tmp174, <variable>.state
#APP
@ 242 "/hihome/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/master_4.4/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC060/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/sw_main.c" 1
	dmb
@ 0 "" 2
	bl	AOE_DeInit	@
	mov	r0, r4	@, tmp174
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
	.fnend
	.size	AoEngineTask, .-AoEngineTask
	.global	g_u64BeginPts
	.global	g_u64EndPts
	.global	g_u16SchTimeoutCnt
	.global	g_u16ExcuteTimeoutCnt
	.global	g_u32cnt
	.section	.rodata
	.align	3
.LANCHOR1 = . + 0
	.type	__func__.26446, %object
	.size	__func__.26446, 20
__func__.26446:
	.ascii	"SchedStatisticsStop\000"
	.space	4
	.type	ktime_zero.9438, %object
	.size	ktime_zero.9438, 8
ktime_zero.9438:
	.space	8
	.section	.rodata.str1.4,"aMS",%progbits,1
	.align	2
.LC0:
	.ascii	"AfltEngineTask\000"
	.space	1
.LC1:
	.ascii	"AoEngineTask\000"
	.space	3
.LC2:
	.ascii	"Sch TimeOut %d\012\000"
	.bss
	.align	3
.LANCHOR0 = . + 0
	.type	g_AfltTaskstate, %object
	.size	g_AfltTaskstate, 4
g_AfltTaskstate:
	.space	4
	.type	g_AfltRunningFlag, %object
	.size	g_AfltRunningFlag, 4
g_AfltRunningFlag:
	.space	4
	.type	g_pstAFLTEThread, %object
	.size	g_pstAFLTEThread, 4
g_pstAFLTEThread:
	.space	4
	.type	task_bug.26509, %object
	.size	task_bug.26509, 4
task_bug.26509:
	.space	4
	.type	g_AoeTaskstate, %object
	.size	g_AoeTaskstate, 4
g_AoeTaskstate:
	.space	4
	.type	g_AoeRunningFlag, %object
	.size	g_AoeRunningFlag, 4
g_AoeRunningFlag:
	.space	4
	.type	g_pstAOEThread, %object
	.size	g_pstAOEThread, 4
g_pstAOEThread:
	.space	4
	.space	4
	.type	g_u64BeginPts, %object
	.size	g_u64BeginPts, 8
g_u64BeginPts:
	.space	8
	.type	g_u64EndPts, %object
	.size	g_u64EndPts, 8
g_u64EndPts:
	.space	8
	.type	g_u16SchTimeoutCnt, %object
	.size	g_u16SchTimeoutCnt, 2
g_u16SchTimeoutCnt:
	.space	2
	.type	g_u16ExcuteTimeoutCnt, %object
	.size	g_u16ExcuteTimeoutCnt, 2
g_u16ExcuteTimeoutCnt:
	.space	2
	.type	g_u32cnt, %object
	.size	g_u32cnt, 4
g_u32cnt:
	.space	4
	.type	u64TimeLast.26271, %object
	.size	u64TimeLast.26271, 8
u64TimeLast.26271:
	.space	8
	.type	u64TimeBase.26270, %object
	.size	u64TimeBase.26270, 8
u64TimeBase.26270:
	.space	8
	.type	task_bug.26472, %object
	.size	task_bug.26472, 4
task_bug.26472:
	.space	4
	.ident	"GCC: (Hisilicon_v200(gcc4.4-290+glibc-2.11+eabi+nptl)) 4.4.1"
	.section	.note.GNU-stack,"",%progbits
