LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_STATIC_JAVA_LIBRARIES := hiVideoPlayer-pinyin4j-2.5.0
LOCAL_STATIC_JAVA_LIBRARIES += HiMediaPlayer
LOCAL_STATIC_JAVA_LIBRARIES += HiBDInfo
LOCAL_STATIC_JAVA_LIBRARIES += DisplaySetting
LOCAL_STATIC_JAVA_LIBRARIES += SDKInvoke
LOCAL_STATIC_JAVA_LIBRARIES += HiDVDInfo

LOCAL_SRC_FILES := $(call all-java-files-under, src)

LOCAL_PACKAGE_NAME := HiVideoPlayer
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_PACKAGE_NAME)
LOCAL_CERTIFICATE := platform
#LOCAL_PROGUARD_FLAG_FILES := proguard.cfg
LOCAL_PROGUARD_ENABLED := disabled
include $(BUILD_PACKAGE)

include $(CLEAR_VARS)
LOCAL_PREBUILT_STATIC_JAVA_LIBRARIES := hiVideoPlayer-pinyin4j-2.5.0:lib/pinyin4j-2.5.0.jar
LOCAL_MODULE_TAGS := optional

include $(BUILD_MULTI_PREBUILT)
