#include "tee_common.h"
#include "tee_config.h"
#include "tee_internal_api.h"
#include "ta_framework.h"
#include "sre_access_control.h"


#define DEFAULT_STACK_SIZE      0x4000
#define VFMW_TASK_STACK_SIZE    0x19000
#define DEFAULT_HEAP_SIZE       0x10000
#define UT_TASK_DEFAULT_HEAP_SIZE 0x100000      //size 1M
//build in service propertys
TA_property_t build_in_service_property[] = {
    /* uuid               stack  heap  permissions  instance  sessin  alive*/
    {TEE_SERVICE_ECHO,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   false},
    {TEE_SERVICE_STORAGE, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
    {TEE_SERVICE_UT,      DEFAULT_STACK_SIZE*2, DEFAULT_HEAP_SIZE, true,     false,  false},
#if !(defined(WITH_STB_PLATFORM) || defined(WITH_DPT_PLATFORM))
    {TEE_SERVICE_CRYPT,   DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
    {TEE_SERVICE_EFUSE,   DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
    {TEE_SERVICE_HDCP,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
    {TEE_SERVICE_KEYMASTER, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE*8, true,     true,   true},
    {TEE_SERVICE_GATEKEEPER, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
    {TEE_SERVICE_SECBOOT, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
    {TEE_SERVICE_IMAXCRYPTO, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
    {TEE_SERVICE_REET, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true, false,   true},
#if !(defined(WITH_STB_PLATFORM) || defined(WITH_DPT_PLATFORM))
    {TEE_SERVICE_TUI_KEYBOARD,  DEFAULT_STACK_SIZE, UT_TASK_DEFAULT_HEAP_SIZE, true, false,   true},
    {TEE_SERVICE_MDPP,    DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
#ifdef WITH_HISI_DEMO
	{TEE_SERVICE_HISI_DEMO, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     false,   true},
#endif
#ifdef WITH_HISI_SEC_MMZ
	{TEE_SERVICE_SEC_MMZ, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
#ifdef WITH_HISI_VFMW
	{TEE_SERVICE_VFMW, VFMW_TASK_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
#ifdef WITH_HISI_TEST
	{TEE_SERVICE_HISI_TEST, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
#ifdef WITH_HISI_SMMU
	{TEE_SERVICE_SMMU, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
#ifdef WITH_HISI_WIDEVINE
    {TEE_SERVICE_WIDEVINE, 200*1024,           900*1024,          true,     true,   true},
#endif
#ifdef WITH_HISI_DMX
        {TEE_SERVICE_DMX, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
#ifdef WITH_HISI_PVR	
    {TEE_SERVICE_PVR, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif	
#ifdef WITH_HISI_SEC_HDMI
	{TEE_SERVICE_HDMI, DEFAULT_STACK_SIZE, DEFAULT_HEAP_SIZE, true,     true,   true},
#endif
    {TEE_SERVICE_SSA, DEFAULT_STACK_SIZE*2, DEFAULT_HEAP_SIZE*8, true,     false,   true},
};

uint32_t build_in_service_property_num = sizeof(build_in_service_property)/sizeof(build_in_service_property[0]);


#if defined(WITH_STB_PLATFORM) || defined(WITH_DPT_PLATFORM)
TEE_UUID build_in_uuid[] = {
	TEE_SERVICE_GLOBAL,
	TEE_SERVICE_STORAGE,
	TEE_SERVICE_REET,
	TEE_SERVICE_ECHO,
#ifdef WITH_HISI_DEMO
	TEE_SERVICE_HISI_DEMO,
#endif
#ifdef WITH_HISI_SEC_MMZ	
	TEE_SERVICE_SEC_MMZ,
#endif
#ifdef WITH_HISI_VFMW
	TEE_SERVICE_VFMW,
#endif
#if WITH_HISI_TEST
	TEE_SERVICE_HISI_TEST,
#endif
#ifdef WITH_HISI_SMMU
	TEE_SERVICE_SMMU,
#endif
#ifdef WITH_HISI_WIDEVINE
    TEE_SERVICE_WIDEVINE,
#endif
#ifdef WITH_HISI_DMX
        TEE_SERVICE_DMX,
#endif
#ifdef WITH_HISI_PVR		
    TEE_SERVICE_PVR,
#endif
#ifdef WITH_HISI_SEC_HDMI
	TEE_SERVICE_HDMI,
#endif
    TEE_SERVICE_SSA,
};
#endif
uint32_t build_in_service_num = sizeof(build_in_uuid)/sizeof(build_in_uuid[0]);

//TA permission control
TA_permission_t ta_permission_config[] = {
	/*internal tasks*/
	{TEE_SERVICE_STORAGE, GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_CRYPT,   GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_EFUSE,   EFUSE_GROUP_PERMISSION},
	{TEE_SERVICE_HDCP,    HDCP_GROUP_PERMISSION | CC_OEM_KEY_GROUP_PERMISSION},
	{TEE_SERVICE_KEYMASTER, GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_SECBOOT, SECBOOT_GROUP_PERMISSION},
	{TEE_SERVICE_IMAXCRYPTO, GENERAL_GROUP_PERMISSION},
	{TEE_SERVICE_REET, SMC_GROUP_PERMISSION},
    {TEE_SERVICE_MDPP, GENERAL_GROUP_PERMISSION | CC_RNG_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION},
#ifdef WITH_HISI_DEMO
	{TEE_SERVICE_HISI_DEMO, ALL_GROUP_PERMISSION},
#endif
    {TEE_SERVICE_SSA, (GENERAL_GROUP_PERMISSION | CC_KEY_GROUP2_PERMISSION | MM_GROUP_PERMISSION)},
#ifdef WITH_HISI_WIDEVINE
	{TEE_SERVICE_WIDEVINE,    GENERAL_GROUP_PERMISSION | MM_GROUP_PERMISSION},
#endif
#ifdef WITH_HISI_SEC_MMZ	
	{TEE_SERVICE_SEC_MMZ, GENERAL_GROUP_PERMISSION | MM_GROUP_PERMISSION},
#endif
#ifdef WITH_HISI_VFMW
	{TEE_SERVICE_VFMW, GENERAL_GROUP_PERMISSION},
#endif
#if WITH_HISI_TEST
	{TEE_SERVICE_HISI_TEST, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION | MM_GROUP_PERMISSION},
#endif
#ifdef WITH_HISI_SMMU
	{TEE_SERVICE_SMMU, GENERAL_GROUP_PERMISSION | MM_GROUP_PERMISSION},
#endif
#ifdef WITH_HISI_DMX
        {TEE_SERVICE_DMX, GENERAL_GROUP_PERMISSION},
#endif
#ifdef WITH_HISI_PVR		
    {TEE_SERVICE_PVR, GENERAL_GROUP_PERMISSION | TIMER_GROUP_PERMISSION},        
#endif	
#ifdef WITH_HISI_SEC_HDMI
	{TEE_SERVICE_HDMI, GENERAL_GROUP_PERMISSION},
#endif
	/*dymanic tasks*/
	{TEE_SERVICE_ECHO, ALL_GROUP_PERMISSION},
	{TEE_SERVICE_TUI_DEMO, TUI_GROUP_PERMISSION|TZASC_GROUP_PERMISSION|HWIMSG_GROUP_PERMISSION},
        // del by fanzongqian {TEE_SERVICE_TUI_KEYBOARD, TUI_GROUP_PERMISSION|TZASC_GROUP_PERMISSION|HWIMSG_GROUP_PERMISSION},
	{TEE_SERVICE_UT,      ALL_GROUP_PERMISSION},
    {TEE_SERVICE_KERNELMEMUSAGE,      ALL_GROUP_PERMISSION},
    {TEE_SERVICE_HELLOWORLD,    GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_TIMER_UT,    TIMER_GROUP_PERMISSION},
    {TEE_SERVICE_PERMCTRL_UT,    GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_FINGERPRINT,    FP_GROUP_PERMISSION|RPMB_GENERIC_PERMISSION | KM_ROT_GROUP_PERMISSION},
    {TEE_FINGERPRINT_COATING_CHECK, FP_GROUP_PERMISSION},
    {TEE_SERVICE_SIGNTOOL,  GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_RPMBKEY,    RPMB_GENERIC_PERMISSION|RPMB_SPECIFIC_PERMISSION },
    {TEE_SERVICE_HUAWEIWALLET,  GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_CRYPTOSMS,  GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_ALIPAY,  GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_WECHAT,  GENERAL_GROUP_PERMISSION},
    {TEE_SERVICE_SKYTONE,    TIMER_GROUP_PERMISSION|RPMB_GENERIC_PERMISSION|VSIM_GROUP_PERMISSION},
    {TEE_SERVICE_Antitheft,    RPMB_GENERIC_PERMISSION },
};
uint32_t dynamic_ta_num = sizeof(ta_permission_config)/sizeof(ta_permission_config[0]);

TA_rpmb_threshold_t ta_rpmb_threshold_config[] = {
    /* DO NOT EDIT */
    {TEE_SERVICE_UT, 0},
    /* DO NOT EDIT */
    {TEE_SERVICE_FINGERPRINT, 0},
    {TEE_SERVICE_RPMBKEY, 10*1024}, // byte unit
    {TEE_SERVICE_SKYTONE, 500*1024},
    {TEE_SERVICE_Antitheft, 20*1024},
#ifdef WITH_HISI_DEMO
	{TEE_SERVICE_HISI_DEMO, 32 * 1024},
#endif	
};
uint32_t g_rpmb_ta_num = sizeof(ta_rpmb_threshold_config)/sizeof(ta_rpmb_threshold_config[0]);

