ifneq ($(CFG_HI_LOADER_APPLOADER),y)
VDEC_DIR := vdec

ifeq (y,$(CFG_HI_VDEC_REG_CODEC_SUPPORT))
LOCAL_CFLAGS += -DHI_VDEC_REG_CODEC_SUPPORT=1
else
LOCAL_CFLAGS += -DHI_VDEC_REG_CODEC_SUPPORT=0
endif

ifeq (y,$(CFG_HI_VDEC_USERDATA_CC_SUPPORT))
LOCAL_CFLAGS += -DHI_VDEC_USERDATA_CC_SUPPORT=1

ifneq (,$(CFG_HI_VDEC_USERDATA_CC_BUFSIZE))
LOCAL_CFLAGS += -DHI_VDEC_USERDATA_CC_BUFSIZE=$(CFG_HI_VDEC_USERDATA_CC_BUFSIZE)
else
LOCAL_CFLAGS += -DHI_VDEC_USERDATA_CC_BUFSIZE=0xC000
endif

else
LOCAL_CFLAGS += -DHI_VDEC_USERDATA_CC_SUPPORT=0
endif

ifeq (y,$(CFG_HI_VDEC_VPU_SUPPORT))
LOCAL_CFLAGS += -DHI_VDEC_VPU_SUPPORT=1
else
LOCAL_CFLAGS += -DHI_VDEC_VPU_SUPPORT=0
endif
ifeq (y,$(CFG_HI_VDEC_MJPEG_SUPPORT))
LOCAL_CFLAGS += -DHI_VDEC_MJPEG_SUPPORT=1
LOCAL_SRC_FILES += $(VDEC_DIR)/mpi_vdec_mjpeg.c
else
LOCAL_CFLAGS += -DHI_VDEC_MJPEG_SUPPORT=0
endif

ifeq (y,$(CFG_HI_VDEC_DFS_SUPPORT))
LOCAL_CFLAGS += -DHI_VDEC_DFS_SUPPORT=1
else
LOCAL_CFLAGS += -DHI_VDEC_DFS_SUPPORT=0
endif

LOCAL_SRC_FILES += $(VDEC_DIR)/hi_codec.c
LOCAL_SRC_FILES += $(VDEC_DIR)/mpi_vdec_adapter.c
LOCAL_SRC_FILES += $(VDEC_DIR)/mpi_vdec.c
ifeq (y,$(CFG_HI_VDEC_VPU_SUPPORT))
LOCAL_SRC_FILES += $(VDEC_DIR)/mpi_vdec_vpu.c
endif
LOCAL_C_INCLUDES += $(MSP_DIR)/drv/vfmw/vfmw_v4.0
LOCAL_C_INCLUDES += $(MSP_DIR)/drv/vdec
LOCAL_C_INCLUDES += $(MSP_DIR)/api/jpeg/inc/inc_6b_android/
LOCAL_C_INCLUDES += $(MSP_DIR)/api/jpeg/inc/inc_hard

endif
