ifdef BOARD_QBSUPPORT
ifeq ($(strip $(BOARD_QBSUPPORT)),true)
ifeq ($(strip $(CHIPNAME)),Hi3798MV100)
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := userapi.bin
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/Emmc
LOCAL_SRC_FILES := userapi.bin
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := hibdrv.bin
ALL_DEFAULT_INSTALLED_MODULES += $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(PRODUCT_OUT)/Emmc
LOCAL_SRC_FILES := hibdrv.bin
include $(BUILD_PREBUILT)
endif
endif
endif
