#ifndef __TDE_CONFIG_H__
#define __TDE_CONFIG_H__

#ifdef HI_ADVCA_FUNCTION_RELEASE
#define CONFIG_TDE_PROC_DISABLE
#define CONFIG_TDE_VERSION_DISABLE
#define CONFIG_TDE_STR_DISABLE
#define CONFIG_TDE_DEBUG_DISABLE
#endif

#endif
