#ADD PLATFORM MACRO HERE
ifeq ($(strip $(WITH_HI3798CV2X_PLATFORM)), true)
TRUSTEDCORE_LOCAL_CFLAGS += -DWITH_HI3798CV2X_PLATFORM
endif

TRUSTEDCORE_LOCAL_CFLAGS += -fno-short-enums

TRUSTEDCORE_LOCAL_CFLAGS += -DCHIP_TYPE_$(HI_CHIP_TYPE)

ifeq ($(WITH_NEON_SUPPORT) , true)
TRUSTEDCORE_LOCAL_CFLAGS += -mfloat-abi=softfp -mfpu=neon
TRUSTEDCORE_LOCAL_CFLAGS += -DCONFIG_NEON_SUPPORT
endif

include $(PLATFORM_DIR)/module_list.mak

ifeq ($(strip $(WITH_CLEAR_BOOT)), true)
TRUSTEDCORE_LOCAL_CFLAGS += -DWITH_CLEAR_BOOT
endif

ifeq ($(strip $(WITH_ARMV8_SUPPORT)), true)
TRUSTEDCORE_LOCAL_CFLAGS  += -DWITH_ARMV8_SUPPORT
TRUSTEDCORE_LOCAL_CFLAGS  += -DATF_MEM_SIZE=$(ATF_MEM_SIZE)
endif

TRUSTEDCORE_LOCAL_CFLAGS += -DTRUSTEDCORE_RAM_TOTAL_AMOUNT=$(TRUSTEDCORE_RAM_TOTAL_AMOUNT)
TRUSTEDCORE_LOCAL_CFLAGS += -DTRUSTEDCORE_RAM_ORDER=$(TRUSTEDCORE_RAM_ORDER)
TRUSTEDCORE_LOCAL_CFLAGS += -DTRUSTEDCORE_KERNEL_MEM_SIZE=$(TRUSTEDCORE_KERNEL_MEM_SIZE)
TRUSTEDCORE_LOCAL_CFLAGS += -DTRUSTEDCORE_SEC_MMZ_MEM_SIZE=$(TRUSTEDCORE_SEC_MMZ_MEM_SIZE)
TRUSTEDCORE_LOCAL_CFLAGS += -DTRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE=$(TRUSTEDCORE_SEC_SMMU_PAGETABLE_SIZE)

ifeq ($(strip $(WITH_GP_V1_1_SUPPORTED)), true)
$(info --- GP_V1_1_SUPPORTED ---)
TRUSTEDCORE_LOCAL_CFLAGS += -DGP_V1_1_SUPPORTED
endif
